#! /bin/sh
#
# Copyright Brother Industries,Ltd 2006-2014
# Sanitized by (c) 2019 Jiri Benc <jbenc@upir.cz>
#
#                                    Ver1.05

# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place, Suite 330, Boston, MA  02111-1307  USA
#

printer=@@MODEL@@

[[ -z $PPD ]] && PPD=/usr/share/cups/model/Brother/${printer}.ppd

/opt/brother/Printers/$printer/cupswrapper/brcupsconfig4 $printer $PPD 0 "$5" >> /dev/null

if [[ $# -ge 7 ]]; then
	cat "$6"
else
	cat
fi | /opt/brother/Printers/$printer/lpd/filter_$printer
